### PR TITLE
#184752109 Buyer should be able to clear their cart

### PR DESCRIPTION
**Pull request by ReneNtabana**
## What does this PR do?
It clears the cart on the buyer session
## Description of Task to be completed?
- The backend handles the clearing of the buyer's cart, including emptying the cart in the buyer's session.
## How should this be manually tested?
- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout <branch-name>`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?
[184752109
Screenshot (228)
Screenshot (229)
](https://www.pivotaltracker.com/story/show/184752109)

### CODE REVIEW

**Review by bergad37 — APPROVED** [review]

**Comment by bergad37** [comment]
A complete task, with simple codes to ready. Well done! Happy coding!

**Review by irakevine — APPROVED** [review]
You've done well, keep it up

**Review by frankflej — APPROVED** [review]
Well done Rene!

**Review by nishimweprince — APPROVED** [review]
The task is perfectly done!

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
