### PR TITLE
#184752105 Feedback and rating on product

### PR DESCRIPTION
**Pull request by frankflej**
## What does this PR do?

This PR is responsible for allowing feedback and rating on products

## Description of Task to be completed?

- This task helps a buyer who purchased a product give feedbacks on it
- This task helps a buyer who purchased a product give ratings on it
- This task also includes the features of viewing all feedbacks on a particular product
- This PR also includes modification on routes which were including id of the logged in user.
## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?
[#184752105](https://www.pivotaltracker.com/story/show/184752105)
## Screenshots (if appropriate)

Screen Shot 2015-08-17 at 2 04 30 PM
Screen Shot 2015-08-16 at 2 51 46 PM
Screen Shot 2015-08-17 at 10 44 42 AM
Screen Shot 2015-08-17 at 10 45 13 AM

### CODE REVIEW

**Review by ReneNtabana — APPROVED** [review]
nice work Frank.

**Review by jcharles921 — APPROVED** [review]
Perfect 👌🏽

**Review by nishimweprince — APPROVED** [review]
This is perfect!!

**Review by bergad37 — COMMENTED** [review]
The work is perfect, everything is being checked before performing the actual work.Comments titles make it easy to understand the codes.

**Review by bergad37 — APPROVED** [review]

**Review by Gabriel-mdv — APPROVED** [review]
You did well fixing tests!

**Review by irakevine — APPROVED** [review]

**Review by niyontwali — APPROVED** [review]

**Review by cyubahiro367 — APPROVED** [review]
you did a great work

**Pull request merged**
