### PR TITLE
#184752117 Seller receives in-app and email notifications

### PR DESCRIPTION
**Pull request by nishimweprince**
## What does this PR do?

This PR allows a user to receives in-app and email notifications when a product life cycle changes

## Description of Task to be completed?

A seller (owner of the product) receives an email and in-app notifications when a product is updated in any of the following cases:
- A product is: `created, updated, expiring`
- An order on the product is: `created, paid for`

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout ft-notifications-184752117`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

- Refer to the API's documentation available on this address: `http://localhost:{PORT}/api/docs`

- Open the browser and navigate to `http//:localhost:{PORT}/notifications` to test a visual demo of in-app notifications

## Any background context you want to provide?

A new relation called `notification` which is associated with `user` is added into the database.

## What are the relevant pivotal tracker/Trello stories?

- [#184752117](https://www.pivotaltracker.com/story/show/184752117)

## Screenshots - if applicable
notification-sc

### CODE REVIEW

**Review by Reennee — APPROVED** [review]
Nice work!!

**Review by jcharles921 — APPROVED** [review]
Wonder full

**Review by irakevine — APPROVED** [review]
Great work!

**Review by Dyves1 — APPROVED** [review]
perfect! sellers need to get notifications

**Review by frankflej — APPROVED** [review]
NIce work!

**Review by niyontwali — APPROVED** [review]
Thanks for the great work!

**Pull request merged**
