### PR TITLE
#184842259 Automated Postgresql Backups with NodeJS

### PR DESCRIPTION
**Pull request by mken1205**
## What does this PR do?

 This PR backs up the database automatically and can restore the database after deletion

## Description of Task to be completed?

- Implement backup script in NodeJS, with error handling and logging mechanisms
- Test the backup script in a staging environment, with different database sizes and configurations
- Set up automated backup job scheduling using a task runner or cron job

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## Any background context you want to provide?

The screenshot provided is the backup database  

## What are the relevant pivotal tracker/Trello stories?

[#184842259](https://www.pivotaltracker.com/story/show/184842259)

## Screenshots (if appropriate)

WhatsApp Image 2023-04-23 at 21 34 53

### CODE REVIEW

**Review by ReneNtabana — APPROVED** [review]
good work Ken

**Review by jcharles921 — APPROVED** [review]
Amazing work , nicely done

**Review by nishimweprince — APPROVED** [review]
Great work!!

**Review by frankflej — APPROVED** [review]
Thats a nice work and important feature

**Review by irakevine — APPROVED** [review]
Good Job

**Pull request merged**
