### PR TITLE
#184797946: Admin can  perform CRUD operation on  products

### PR DESCRIPTION
**Pull request by bergad37**
### What does this PR do?
Admin should be able to perfom  CRUD operations on  products in stock

### Description of Task to be completed?

- Admin can crud the product
- Admin can delete, update, read, and add a product in the stock.

### How should this be manually tested?

- Clone the repository using git clone [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)
- Install node packages that the application depends on: `npm i`
- Checkout to the branch using `git checkout ft-admin-crud-products-184797946`
- 
- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in the application's root directory.
- Start the application development server: `npm run dev` ,and test admin routes

## Any background context you want to provide?

- The user has full access to the products in the stock regardless the owner of the product

## What are the relevant pivotal tracker/Trello stories?
[#184797946](https://www.pivotaltracker.com/story/show/184797946)

## Screenshots 
Screen Shot 2023-04-23 at 23 55 10

Screen Shot 2023-04-23 at 11 11 54
Screen Shot 2023-04-23 at 15 57 10

Screen Shot 2023-04-23 at 15 55 36

### CODE REVIEW

**Review by frankflej — COMMENTED** [review]
can you please change on `src/docs/Admin/getASingleProduct` and  `src/docs/Product/getASingleProduct` there are some mistakes in displayed messages on operationId and description you are getting a single product, otherwise your code is very well built nice job!!!

**Comment by bergad37** [comment]
Thanks, i have made changes!

**Review by Gabriel-mdv — APPROVED** [review]
I see a great work.

**Review by jcharles921 — APPROVED** [review]
A great and  meticulous Job done by you . ✨✨✨ i specialty appreciated the work done on documentation  and test. 👍🏽

**Review by irakevine — APPROVED** [review]
I think this is a good PR, I'm happy with how well all the routes are working on the swagger documentation and passing all the tests. You did a great job

**Review by frankflej — APPROVED** [review]

**Review by cyubahiro367 — APPROVED** [review]
u did a great work

**Comment by bergad37** [comment]
Thanks!, a notification feature sent to the owner of the product for every product deleted or updated by `Admin` is to be implemented once we are done with the task of `Notifications`.

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
