### PR TITLE
#184752118 Public real-time chatroom for users

### PR DESCRIPTION
**Pull request by nishimweprince**
## What does this PR do?

This PR allows logged in users to share messages in a chatroom publicly and in real-time

## Description of Task to be completed?

Only when a **user** is logged in and they open a chat tab, they read all messages sent by other users and can add their messages in real time. When a user shares a message, all users who are online receives the message instantly, and others who log in later can read the messages.

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Install node packages that the application depends on: `npm i`

- Checkout to the branch using `git checkout ft-chatroom-184752118`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

- Open the browser and navigate to this address: `http://localhost:{PORT}/chat` to access the chatroom.

## Any background context you want to provide?

I have modified the `user` relation to add the **image** attribute/column.

## What are the relevant pivotal tracker/Trello stories?

1. [#184752118](https://www.pivotaltracker.com/story/show/184752118)

## Screenshots (if appropriate)

user-connected
user-leaves

### CODE REVIEW

**Review by frankflej — APPROVED** [review]
I see a hard work in here and the code is clean this looks proffessional keep it up!

**Review by Dyves1 — APPROVED** [review]
wow! You used `frontend` here, its very nice for sure

**Review by ReneNtabana — APPROVED** [review]

**Comment by ReneNtabana** [comment]
It looks nice and it looks very nice

**Comment by ReneNtabana** [comment]
You did great and it looks really nice

**Review by irakevine — APPROVED** [review]
GoodJob

**Review by Gabriel-mdv — APPROVED** [review]
This work is lit. Kudos

**Review by jcharles921 — APPROVED** [review]
Great work ✨✨✨ 👏🏾

**Review by bergad37 — APPROVED** [review]

**Review by niyontwali — APPROVED** [review]
Well done!

**Pull request merged**
