### PR TITLE
#184752093 two-factor-authentication-for-seller

### PR DESCRIPTION
**Pull request by Tparfaite**
## What does this PR do?
- Two Factor Authentication option is enabled on vendor login
- Appropriate error messages are returned on unsuccessful attempts

## Description of Task to be completed?
- Two-factor authentication is enabled on seller login
- Token is generated and sent to the seller via email with an expiration time by using nodeMailer
- The seller will use the generated token to be verified.
- If the verification succeeded, isVerified with be true and the seller will be assigned a new token

## How should this be manually tested?
- Clone the repo 
- Install the packages by running " **npm install**"
- checkout to ft-two-factor-authentication by typing git checkout **ft-two-factor-authentication-184752093**
- Create a **.env** file in the root directory and add all environment variables required to run the application. The required variables are listed in the **.env.example** file available in root directory of the application.
- Start the application development server by: **npm run dev**

## Any background context you want to provide?
- You need to have credentials for a seller to be able to log in using the login route
- Once you've received the email(token), use documented authorization routes

## What are the relevant pivotal tracker/Trello stories?
#184752093

### CODE REVIEW

**Comment by bergad37** [comment]
PR well structured ,but few error in description to refer to markup writing  ,like  on the section of clone the `repo` , command to switch to your repository  `git checkout ft-two-factor-authentication` , `npm install`,  creating `.env` file ,  mentioning `env.example` and the start command of `npm run dev`.

**Review by bergad37 — COMMENTED** [review]
PR well structured ,but few typo error in description to refer to markup writing ,like on the section of clone the `repo` , command to switch to your repository `git checkout ft-two-factor-authentication `,` npm install`, creating `.env` file , mentioning `.env.example` and the start command of `npm run dev`.

**Review by nishimweprince — APPROVED** [review]
Excellent work!!

**Review by frankflej — APPROVED** [review]
great

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
