### PR TITLE
#004 Fixing Admin Product Creation

### PR DESCRIPTION
**Pull request by mken1205**
## What does this PR do?

This PR fixes the creation of a new product by admin to include the ID of the seller instead of the admin on the product

## Description of Task to be completed?

As an Admin, when creating a new product in the system, it's important to note that each product is intended for a specific seller. Therefore, it's necessary to include the Seller ID when creating a product to ensure that it's added to the seller's inventory/stock and is available for purchase.

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?

[#185027687](https://www.pivotaltracker.com/story/show/185027687)

### CODE REVIEW

**Review by jcharles921 — APPROVED** [review]
LGTM

**Review by nishimweprince — APPROVED** [review]
Great fix !!

**Review by ReneNtabana — APPROVED** [review]
Good job fixing the issue Ken

**Review by bergad37 — APPROVED** [review]
Well done!

**Review by frankflej — APPROVED** [review]
Awesome work!

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
