### PR TITLE
#185026087 Improve Swagger Docs for user notification

### PR DESCRIPTION
**Pull request by nishimweprince**
## What does this PR do?

This PR improves Swagger Documentation of User in-app and email notifications feature.

## Description of Task to be completed?

- Adds missing endpoints documentation for user notification feature
- Improves organization of Swagger components in our codebase

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout bg-update-swaggerdocs-185026087`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

- Refer to the application's API Documentation available on this link: `http://localhost:{PORT}/api/docs`

## Any background context you want to provide?

This PR is checked-out from the default branch `develop` which at the time had lower code coveralls percentage, and it will also fall below the required threshold of `80%`.

## What are the relevant pivotal tracker/Trello stories?

- [#185026087](https://www.pivotaltracker.com/story/show/185026087)

## Screenshots (if appropriate)

swagger

### CODE REVIEW

**Review by Reennee — APPROVED** [review]

**Review by Gabriel-mdv — APPROVED** [review]
swagger is well improved!

**Review by Dyves1 — APPROVED** [review]
well

**Review by ReneNtabana — APPROVED** [review]
Nice work!

**Review by irakozejules — APPROVED** [review]

**Review by frankflej — APPROVED** [review]
Nice work!

**Review by irakevine — APPROVED** [review]

**Review by niyontwali — APPROVED** [review]
Well done

**Pull request merged**
