### PR TITLE
#184752096  Setting roles and permissions 

### PR DESCRIPTION
**Pull request by ReneNtabana**
## What does this P.R. do?
It gives the admin permission to manage other users.
## Description of Task to be completed?
Admin should be able to assign various users to various roles. There should also be a role for the admin account itself. This will allow only accounts with particular roles permission to perform particular actions.
## How should this be manually tested?
-Clone the repo and checkout to ft-authorisation-184752096 by typing `git checkout ft-authorization-184752096`
-Install the packages by running `npm install`
-Create a .env file in the root directory and add all environment variables required to run the application. The required variables are listed in the .env.example file available in the root directory of the application.  
-Start the application development server: `npm run dev`
## What are the relevant pivotal tracker/Trello stories?
#184752096

### CODE REVIEW

**Review by frankflej — APPROVED** [review]
Thats great

**Review by jcharles921 — APPROVED** [review]

**Review by nishimweprince — APPROVED** [review]
Excellent work!!

**Review by Gabriel-mdv — APPROVED** [review]
great work done.

**Review by niyontwali — APPROVED** [review]
Well done

**Pull request closed without merging**
