### PR TITLE
#184797945 CRUD operations on order 

### PR DESCRIPTION
**Pull request by frankflej**
## What does this PR do?
This is PR is responsible for the create, update and delete of an order
## Description of Task to be completed?
This task prompts a buyer to be able to **create** an order in the order table, it also gives him the permission to **update** and also the capabality to **delete** his own order.
## How should this be manually tested?
- Clone the repository using git clone [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)
- Install node packages that the application depends on: `npm install`
- Checkout to the branch using git checkout <branch-name>
- Create a .env file in the root directory and add all environment variables required to run the application. The required variables are listed in the .env.example file available in root directory of the application.
- Start the application development server: `npm run dev`
- Finally use any testing environment of your choice to test the order routes
## What are the relevant pivotal tracker/Trello stories?
[#184797945](https://www.pivotaltracker.com/story/show/184797945)
## Screenshots (if appropriate)
Screen Shot 2015-08-11 at 12 34 55 AM
Screen Shot 2015-08-10 at 6 46 28 PM

Screen Shot 2015-08-11 at 12 34 41 AM

### CODE REVIEW

**Review by bergad37 — APPROVED** [review]
Great work!

**Review by jcharles921 — APPROVED** [review]
Great Job

**Review by nshutijonathan — COMMENTED** [review]
add relevant screenshoot

**Review by nishimweprince — APPROVED** [review]
Excellent work!!

**Review by irakevine — COMMENTED** [review]
Great Work

**Review by niyontwali — APPROVED** [review]
Well done

**Pull request merged**
