### PR TITLE
#184752106 User/buyer should be able to add items to their cart

### PR DESCRIPTION
**Pull request by Dyves1**
## What does this PR do?
- User/buyer should be able to add items to their cart
## Description of Task to be completed?
- The item should be added to the buyer's cart
- The product details (name, price, image) should be retrieved from the database
-  The new cart total should be calculated and saved to the buyer's account or session
- A confirmation message should be sent to the front to be displayed to the buyer 
## How should this be manually tested?
- Clone the repo `git clone`  [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)
- Run `run npm install` in order to install dependencies which are listed in `package.json`
- Create `.env` file in the root directory
- Copy and paste the content `.env.example` into `.env` set the appropriate PORT and other listed environment variables
- Run `npm run dev` for development

## What are the relevant pivotal tracker/Trello stories?
[184752106](https://www.pivotaltracker.com/story/show/184752106)

## Screenshot

Screenshot (307)

### CODE REVIEW

**Review by jcharles921 — DISMISSED** [review]

**Review by jcharles921 — COMMENTED** [review]
Great work but Rebase your work

**Review by jcharles921 — APPROVED** [review]
Good Job

**Comment by ReneNtabana** [comment]
good job

**Review by ReneNtabana — APPROVED** [review]

**Review by frankflej — APPROVED** [review]
Perfect!

**Review by irakevine — APPROVED** [review]
Great Work

**Review by niyontwali — APPROVED** [review]

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
