### PR TITLE
#184752085 ft-seller-statisics

### PR DESCRIPTION
**Pull request by Tparfaite**
## What does this PR do?
- To let A Seller see their statistics in a given time-frame

### display key metrics such as:
1.  Total revenue
2. Number of orders
3. Products sold
4. Money made in time-frame
5. Top selling products

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout ft-seller-statistics-184752085`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?
[#184752085(https://www.pivotaltracker.com/story/show/184752085)
## Screenshots (if appropriate)
Screen Shot 2015-08-24 at 8 46 08 AM
Screen Shot 2015-08-24 at 8 47 31 AM

### CODE REVIEW

**Review by jcharles921 — APPROVED** [review]

**Review by ReneNtabana — APPROVED** [review]

**Review by Dyves1 — APPROVED** [review]

**Review by frankflej — APPROVED** [review]
Nice work!

**Review by bergad37 — APPROVED** [review]

**Review by Gabriel-mdv — APPROVED** [review]
Great work and I like these new changes.

**Review by nishimweprince — APPROVED** [review]
Excellent work!!

**Review by irakozejules — APPROVED** [review]

**Review by irakevine — APPROVED** [review]
Great Work

**Review by niyontwali — APPROVED** [review]

**Review by cyubahiro367 — APPROVED** [review]

**Pull request merged**
