### PR TITLE
#184797944 Implement custom database seeders script          

### PR DESCRIPTION
**Pull request by irakevine**
## What does this PR do?
Implementation  of seeders in database script. 

## Description of Task to be completed?
- Creation of user, role, product, payment, cart, category and order tables/models with sequelize. 
- addition of dummy data in user table and role table.
- addition of dummy data in product table and order table.
- addition of dummy data in payment table and cart table.

## How should this be manually tested?
- Clone the repo using `git clone` repo.
- Run `npm install` from the directory root.
- Create a `.env`  to store sensitive credentials used in this application. Make sure to check `.env.example` to find all environment variables.
- Run `npm run dev` to check if database is connected.
- Run `npm run migrate` to check if migrations is running.
- Run `npm run seed` if you want to insert data  in database .

## What are the relevant pivotal tracker/Trello stories?
#184797944

### CODE REVIEW

**Review by nishimweprince — CHANGES_REQUESTED** [review]
Please fix conflicts that arise with CircleCI configuration. Below is what you can try:
- Adopt changes made on the [ch-integrate_Circleci-184752080](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn/tree/ch-integrate_Circleci-184752080) branch. Pull from `origin develop` to update your local version of the repo, then rebase with your branch to keep it in sync.

**Review by frankflej — APPROVED** [review]
This is perfect

**Review by bergad37 — APPROVED** [review]

**Review by nishimweprince — APPROVED** [review]
Perfect!!

**Review by nishimweprince — APPROVED** [review]
Perfect!!

**Review by jcharles921 — APPROVED** [review]
Excellent work 👍✨✨✨

**Review by nishimweprince — APPROVED** [review]
This is great setup!

**Review by frankflej — APPROVED** [review]

**Review by niyontwali — APPROVED** [review]
Well done

**Pull request merged**
