### PR TITLE
#185108426 Ft Code climate maintainablity badge

### PR DESCRIPTION
**Pull request by mken1205**
## What does this PR do?

It adds a code coverage badge to the readme file

## Description of Task to be completed?
on code-climate we generate a checkup on the code base to find duplication or other issues that may come in it.
Go to settings of code climate then generate the badge on the corresponding tab
## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?
[#185108426](https://www.pivotaltracker.com/story/show/185108426)

### CODE REVIEW

**Review by bergad37 — APPROVED** [review]

**Review by jcharles921 — APPROVED** [review]
Great 👍

**Review by frankflej — APPROVED** [review]
Thanks for adding that too!!

**Review by Dyves1 — APPROVED** [review]
Well done

**Review by ReneNtabana — APPROVED** [review]

**Review by Gabriel-mdv — APPROVED** [review]
Well done.

**Review by irakevine — APPROVED** [review]
It's great that you thought this was important! that would be good.,
you did well!

**Review by Tparfaite — APPROVED** [review]

**Review by niyontwali — APPROVED** [review]
Well done

**Pull request merged**
