### PR TITLE
#184752077 Configure eslint

### PR DESCRIPTION
**Pull request by ReneNtabana**
## What does this PR do?
This PR sets up es-lint to check syntax error and enforce formatting style.
## Description of Task to be completed?
ESLint is the required linter for the project. It'll help check for style violations and flag them.
## How should this be manually tested?
1. Clone the repo
2. Cd into that repo
3. run npm install
4. After that run npm run dev
## Any background context you want to provide?
- I have configured ESLint to use Javascript module because it is the style convention we will be using throughout the development process.
## What are the relevant pivotal tracker/Trello stories?
1. [#184752077](https://www.pivotaltracker.com/story/show/184752077)

### CODE REVIEW

**Review by nshutijonathan — CHANGES_REQUESTED** [review]
- Rename your PR title to `#184752077 Configure  eslint`  
- Rename your commit message to `chore(set-up):configured eslint` 
- What are the relevant pivotal tracker/Trello stories // #184752077 ,that ID should be clickable or hyperlinked to the PR board

**Review by nishimweprince — APPROVED** [review]
The configuration is great, and the number of commits are in range of maximum of two as require.

**Review by jcharles921 — APPROVED** [review]
Good great work

**Review by niyontwali — APPROVED** [review]
Well done!

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Pull request merged**
