### PR TITLE
#184829218 Admin changes the status of delivered or cancelled 

### PR DESCRIPTION
**Pull request by Gabriel-mdv**
## What does this PR do?
- Admin changes the status of delivered or cancelled orders and the buyer is notified by email

## Description of Task to be completed?

- Admin mark the status of order as delivered
- Ehe user who placed that order gets an emails
- Admin can also mark the order as cancelled when the user request it
- Only admin is allowed to perform this action 

## How should this be manually tested?

- Clone the repo git clone [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)
- Run `run npm` install in order to install dependencies which are listed in `package.json`
- Create `.env` file in the root directory
- Copy and paste the content `.env.example` into `.env` set the appropriate PORT and other listed environment variables
- Run `npm run dev` for development

## What are the relevant pivotal tracker/Trello stories?

 [#184829218](https://www.pivotaltracker.com/story/show/184829218)

### CODE REVIEW

**Review by irakevine — APPROVED** [review]
Great Work

**Review by jcharles921 — APPROVED** [review]
Great Job ,👍

**Review by frankflej — APPROVED** [review]
Nice work

**Review by Dyves1 — APPROVED** [review]
Great Work

**Review by niyontwali — APPROVED** [review]
Well Done

**Pull request merged**
