### PR TITLE
#184752107 Buyer should be able to update their cart

### PR DESCRIPTION
**Pull request by ReneNtabana**
## What does this PR do?
It updates the quantity of a product in the cart
## Description of Task to be completed?
- The updated cart should be stored in the buyer's session
- The product details (name, price, image) should be retrieved from the database for each item in the updated cart
- The new cart total should be calculated by summing the prices of the items in the updated cart
- An updated cart confirmation message should be sent to the frontend to be displayed to the buyer
## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?
[184752107](https://www.pivotaltracker.com/story/show/184752107)
## Screenshots (if appropriate)

Screenshot (230)
Screenshot (231)
Screenshot (232)

### CODE REVIEW

**Review by frankflej — APPROVED** [review]
Plz can you add a screenshot to add more proof!

**Comment by ReneNtabana** [comment]
> Plz can you add a screenshot to add more proof!

I have made the changes

**Review by mken1205 — APPROVED** [review]
Looks Good

**Review by Dyves1 — APPROVED** [review]
This is good to the buyer to update their cart

**Review by irakevine — APPROVED** [review]
It is very good that you add the update operator so that the buyer can have access to update his cart if he wants., keep it up.

**Review by cyubahiro367 — APPROVED** [review]

**Review by bergad37 — APPROVED** [review]
Well done!

**Review by jcharles921 — APPROVED** [review]
LGTM

**Comment by bergad37** [comment]
The issue is, what if the user tries to add more `quantity` than the `quantity` in stock?

**Review by bergad37 — CHANGES_REQUESTED** [review]
I left a comment on the quantity check.

**Review by bergad37 — APPROVED** [review]
Great work!! , all checks are done before placing an order or updating a cart.Happy coding !

**Review by nishimweprince — APPROVED** [review]
Great work !!

**Review by jcharles921 — APPROVED** [review]
Great work ✨

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
