### PR TITLE
 #184752074 Set up an empty Express Boilerplate with dotenv

### PR DESCRIPTION
**Pull request by frankflej**
## What does this PR do?
This PR aims at setting up express and server project
## Description of Task to be completed?

1. Set up an empty Node.js - express application. 
2. By this We mean a full directory with all folders that you think developer will need. this might include but not limited to 
   src/ controllers, models, routes helpers,validations, etc
3.Test
4.  feel free to contact the rest of the team and get ideas from them because this is the first skeleton of the application.
5. Install and setup dotenv for the API to manage environment variables. Ensure packages like sequelize and passport among the rest can fetch data about the current environment correctly via dotenv. Add documentation on how to utilize dotenv in the API.

6. Set the server and make sure it is running

## How should this be manually tested?

1. Clone the repo 
2. Cd into that repo
3. run  `npm install`
4. After that run `npm run dev`

## What are the relevant pivotal tracker/Trello stories?

1. #184752075
2. #184752076
3. #184752078

### CODE REVIEW

**Review by jcharles921 — APPROVED** [review]
it's ok for me

**Comment by nishimweprince** [comment]
The setup is great for me.

**Review by nishimweprince — COMMENTED** [review]
The setup is great for me.

**Review by nshutijonathan — CHANGES_REQUESTED** [review]
- Rename your PR title, It should not be that one, I would go with this `#Pivotal-Tracker-Board-Story-Id   Set up an empty Express Boilerplate with dotenv ` 
- your commit message should be renamed to `chore(set-up):server and express set up` 
-

**Review by niyontwali — APPROVED** [review]
Thanks for applying the feedback. It looks great now

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by nishimweprince — APPROVED** [review]
Adheres with the engineering playbook conventions.

**Review by nishimweprince — APPROVED** [review]
The setup is great, and the naming conventions are correct.

**Pull request merged**
