### PR TITLE
#184752077 Configure ESLint

### PR DESCRIPTION
**Pull request by ReneNtabana**
## What does this PR do?

This PR sets up es-lint to check syntax error and enforce formatting style.

## Description of Task to be completed?

ESLint is the required linter for the project. It'll help check for style violations and flag them.

## How should this be manually tested?

1. Clone the repo
2. Cd into that repo
3. run npm install
4. After that run npm run dev

## Any background context you want to provide?

- I have configured ESLint to use Javascript module because it is the style convention we will be using throughout the development process.

## What are the relevant pivotal tracker/Trello stories?

1. #184752077

### CODE REVIEW

**Review by nishimweprince — APPROVED** [review]
The configuration is great. This PR exceeds two commit messages but we will aim to correct it moving forward.

**Comment by niyontwali** [comment]
@Reennee Here are my feedback to be addressed:

1. Please use `##` for the headings, this will make it look more like a heading instead of looking like a normal text eg. 
## What does this PR do?
2. On the description of task to be completed, refer to the Pivot Tracker description for your task
3. On the section of How should this be manually tested? Please specify clear also how we can test that eslint was configured
4. Please do not exceed 1 (one) commit message. You need to squash your commits to only 1 commit
5. Remember to assign this PR to atleast 5 people. I can only see you assigned it to one person

**Comment by ReneNtabana** [comment]
Changed the number of reviewers and changed the titles

**Review by jcharles921 — APPROVED** [review]
great job :+1:

**Pull request closed without merging**
