### PR TITLE
#005  Fixing Swagger Documentation

### PR DESCRIPTION
**Pull request by jcharles921**
## What does this PR do?
This PR fixes the documentation for some features which were not working
## Description of Task to be completed?
The following are to be fixed : 
- the return responses 
-  update order
- delete order
- product search

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?
[#185026087](https://www.pivotaltracker.com/story/show/185026087)

### CODE REVIEW

**Review by bergad37 — APPROVED** [review]
Thanks for handling the routes that were working in postman but failing on swagger. Happy coding!

**Review by niyontwali — APPROVED** [review]
Well done

**Review by mken1205 — APPROVED** [review]
Good job

**Review by Dyves1 — APPROVED** [review]
Great 👍

**Review by ReneNtabana — APPROVED** [review]
Nice work!!

**Review by frankflej — APPROVED** [review]
NIce work

**Review by irakevine — APPROVED** [review]
Great work

**Review by nishimweprince — APPROVED** [review]
Thank you for these fixes, it will help testing our APIs much easier and more effective. Great work!

**Pull request merged**
