### PR TITLE
#184752100 Seller can have access to Delete and Update item 

### PR DESCRIPTION
**Pull request by bergad37**
### What does this PR do?
As a seller, I should delete  or update a specific item in my collection
### Description of Task to be completed?

- A seller can only delete the product belonging to his collection,
- A seller can update an item in the collection 

### How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)
- Install node packages that the application depends on: `npm install`
- Checkout to the branch using `git checkout`
- Create a `.env ` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example`  file available in the application's root directory.
- Start the application development server: `npm run dev`
- productId is decimal integer

### Any background context you want to provide?

- A seller can delete any specific item in the collection only when he is logged in successfully.
- Products not belonging to his collection can not be deleted, 
- A deleted product is removed from the collection permanently
- A seller can update a product details in the collection

What are the relevant pivotal tracker/Trello stories?

- [#184752100](https://www.pivotaltracker.com/story/show/184752100) 
-  [#184752103](https://www.pivotaltracker.com/story/show/184752103)

### CODE REVIEW

**Review by irakevine — APPROVED** [review]
Well Done

**Review by jcharles921 — APPROVED** [review]

**Review by frankflej — APPROVED** [review]
Great

**Review by Dyves1 — APPROVED** [review]
Well  done 👍

**Review by nishimweprince — APPROVED** [review]
Excellent!

**Review by Gabriel-mdv — APPROVED** [review]
I passed throught the work. It is well done.

**Pull request merged**
