### PR TITLE
feature(tracking):Buyer should be able to track their order status

### PR DESCRIPTION
**Pull request by irakozejules**
## What does this PR do?
This PR helps the buyer to track the status of his or her order

## Description of Task to be completed?
-GIVEN a get request for order status information
The appropriate order status information should be retrieved from the database
The order status information should be sent to the frontend to be displayed to the buyer
WHEN the requesting user/token is a buyer and the request is validated
THEN:
The appropriate order status information should be retrieved from the database
The order status information should be sent to the frontend to be displayed to the buyer

-GIVEN a post request to update order status
WHEN the request body is validated and the requesting user/token is an admin
THEN:
The order status in the database should be updated
The updated order status should be sent to the frontend to be displayed to the buyer

## How should this be manually tested?
- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Install node packages that the application depends on: `npm i`

- Checkout to the branch using `git checkout <branch-name>`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?

[184752111](https://www.pivotaltracker.com/story/show/184752111)

## Screenshot
Screen Shot 2023-04-27 at 19 03 17
Screen Shot 2023-04-27 at 19 05 06
Screen Shot 2023-04-27 at 19 08 02
Screen Shot 2023-04-27 at 21 09 02
Screen Shot 2023-04-27 at 21 09 28
Screen Shot 2023-04-27 at 21 09 59
Screen Shot 2023-04-27 at 21 10 40
Screen Shot 2023-04-27 at 21 11 00
Screen Shot 2023-04-27 at 21 11 16

### CODE REVIEW

**Review by Dyves1 — APPROVED** [review]
This feature is very important 
Great work 👍

**Review by cyubahiro367 — APPROVED** [review]
great Job

**Review by ReneNtabana — APPROVED** [review]
good job

**Review by frankflej — APPROVED** [review]
That's a good implentation since the user can track the status of his order.

**Review by irakevine — APPROVED** [review]
Good job really, keep it up

**Review by jcharles921 — APPROVED** [review]
Great work

**Review by bergad37 — APPROVED** [review]

**Review by niyontwali — CHANGES_REQUESTED** [review]
As we discussed, please modify the functionalities. Try to come up with a backend for something that is similar to this. Above all refer to the description for your task on pivot tracker
Screenshot 2023-04-25 at 19 19 19

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
