### PR TITLE
#185548712 Add DM features to chatroom

### PR DESCRIPTION
**Pull request by nishimweprince**
## What does this PR do?

This PR adds a Direct Messages feature to the application's chatroom.

## Description of Task to be completed?

- Two users can chat privately using Direct Messages
- User can join different groups
- Messages shared to a group can only be seen by respective group members
- User can see whether another party is active when chatting.
- User can see a list of active users in a group.

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout ft-chatroom-dm-185548712`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?

- [#185548712](https://www.pivotaltracker.com/story/show/185548712)

### CODE REVIEW

**Review by Dyves1 — APPROVED** [review]

**Review by ReneNtabana — APPROVED** [review]
Nicely done

**Review by frankflej — APPROVED** [review]
This looks great!

**Review by frankflej — APPROVED** [review]
This looks great!

**Review by irakevine — APPROVED** [review]
Great Work!

**Review by jcharles921 — APPROVED** [review]
Excellent job 👍👏🏾

**Pull request merged**
