### PR TITLE
#184752078  Integrate HoundCI with badge attached to readme

### PR DESCRIPTION
**Pull request by Gabriel-mdv**
### What does this PR do?
configure houndci to the project and add its badge into the readme.

### Description of the task completed
* This is to automatically validate the codebase with standard style guides
* Technically HoundCI has no official readme badge but there are services out there with which you can create a HoundCI badge.

### Any background context you want to provide?
As I was supposed to add the badge to the readme file. I necessarily created the readme file and wrote the  content available for now.  It contains some set up instructions for our current progress, and it ```keep beeing updated as we proceed with other in the project```

#### What are the relevant pivotal tracker/Trello stories?
[#184752078](https://www.pivotaltracker.com/n/projects/2635056)

### CODE REVIEW

**Review by nishimweprince — APPROVED** [review]
This looks very good! We will change the heading of our README to `E-Commerce` instead of Libray App.

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by nishimweprince — DISMISSED** [review]
Please configure Hound (`.hound.yml`) to include the `.eslintignore` file as well. You may refer to this [link](http://help.houndci.com/en/articles/2138530-eslint#:~:text=To%20ignore%20certain%20files%20and%20directories%2C)

Thank you.

**Review by jcharles921 — APPROVED** [review]
Great Work 👌👍

**Review by nishimweprince — APPROVED** [review]
Great work @Gabriel-mdv.

**Pull request merged**
