### PR TITLE
#185024129 bg-Fixing coverage bugs and update ReadMe file

### PR DESCRIPTION
**Pull request by Dyves1**
## What does this PR do?

This PR improve the code coverage of automated tests for this project and update the Readme file to ensure users have accurate and up-to-date information.

## Description of Task to be completed?

- Increased code coverage for the project.

- An updated Readme file that accurately reflects the software's features and usage instructions. Please follow the Andela Best practices

- A tested and working software project with improved test coverage and an updated Readme file.

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout bg-Fixing-coverage-bugs-and-update-Read-me-file-185024129`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`

## What are the relevant pivotal tracker/Trello stories?

- [#185024129](https://www.pivotaltracker.com/story/show/185024129)

### CODE REVIEW

**Review by niyontwali — APPROVED** [review]
Well done

**Review by frankflej — APPROVED** [review]
Nice work!

**Review by jcharles921 — APPROVED** [review]

**Review by ReneNtabana — APPROVED** [review]
Nice work!

**Review by nishimweprince — APPROVED** [review]
Excellent fixes!!

**Pull request merged**
