### PR TITLE
#184842143: Logging features

### PR DESCRIPTION
**Pull request by bergad37**
## What does this PR do?

- Configure logging feature for the App

## Description of Task to be completed?

- As an admin, I want to have the logs feature on my website to track user actions and system events. This will help me monitor and troubleshoot any issues that may arise.
- Set up log storage

## How should this be manually tested?

- Clone the repository using `git clone` [link](https://github.com/atlp-rwanda/e-comm-team-techsmith-bn)

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm run dev`
- Logs are stored in a `File` located  in the `root` directory

## Any background context you want to provide?
A framework used for this logging feature is [Winston](https://signoz.io/blog/winston-logger/) 
## What are the relevant pivotal tracker/Trello stories?
[#184842143](https://www.pivotaltracker.com/story/show/184842143)
## Screenshots (if appropriate)
Screen Shot 2023-05-03 at 08 33 52
Screen Shot 2023-05-03 at 08 34 11
Screen Shot 2023-05-03 at 08 34 27

### CODE REVIEW

**Review by jcharles921 — APPROVED** [review]

**Review by Dyves1 — APPROVED** [review]

**Review by Tparfaite — APPROVED** [review]

**Review by cyubahiro367 — APPROVED** [review]

**Review by nishimweprince — APPROVED** [review]
Excellent work!!

**Review by jcharles921 — APPROVED** [review]
Great work

**Review by irakevine — APPROVED** [review]
Great Work

**Review by ReneNtabana — APPROVED** [review]

**Review by frankflej — APPROVED** [review]
Nice work!

**Review by irakozejules — APPROVED** [review]

**Review by mken1205 — APPROVED** [review]
Great execution

**Review by niyontwali — APPROVED** [review]
Well done

**Pull request merged**
